- alias: weather_report
  initial_state: true
  trigger:
    - platform: time
      hours: 7
      minutes: 30
      seconds: 0
      
  condition:
    condition: numeric_state
    entity_id: sensor.weather_temperature
    above: 0  #判断气温是否高于34°C
        
  action:
    - service: tts.baidu_say
      data_template:
        entity_id: media_player.vlc
        message: "现在播报天气信息。温度，{{states('sensor.weather_temperature')}}°C, 湿度{{states('sensor.weather_humidity')}}，风速{{states('sensor.weather_wind_speed')}}, 气压{{states('sensor.weather_pressure')}}"